//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Book
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public int Edition { get; set; }
        [DataType(DataType.DateTime)]
        public System.DateTime ReleaseDate { get; set; }
        public int Writer { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
